experiment_name: read_classification

input: 
  sample table: inputs/samples.tsv
  adapter_file: inputs/all_illumina_adapters.fa
  cycog_file: inputs/cycog_len.tsv
  nodes_file: /path/to/ProSynTaxDB_nodes.dmp
  names_file: /path/to/ProSynTaxDB_names.dmp
  fmi_file: /path/to/ProSynTaxDB.fmi
  diamond_file: /path/to/CyCOG6.dmnd
  

classification_summary:
  # list of genus to extract read count for (remaining genus will be summed into "other_genus")
  genus_list: ['Synechococcus', 'Prochlorococcus', 'unclassified']

scratch directory: scratch
results directory: results
